"""Constants for the Qolsys Panel integration."""

DOMAIN = "qolsys_panel"
CONF_RANDOM_MAC = "random_mac"
CONF_IMEI = "imei"
OPTION_MOTION_SENSOR_DELAY_ENABLED = "motion_sensor_delay_enabled"
OPTION_MOTION_SENSOR_DELAY = "motion_sensor_delay"
SERVICE_TRIGGER_POLICE = "trigger_police"
SERVICE_TRIGGER_AUXILLIARY = "trigger_auxilliary"
SERVICE_TRIGGER_FIRE = "trigger_fire"
